package example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MeetingRoom implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label("capacity")
   private int capacity;

   public MeetingRoom()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public int getCapacity()
   {
      return this.capacity;
   }

   public void setCapacity(int capacity)
   {
      this.capacity = capacity;
   }

   public MeetingRoom(java.lang.String name, int capacity)
   {
      this.name = name;
      this.capacity = capacity;
   }

}