package example;

import org.optaplanner.core.impl.domain.solution.AbstractSolution;
import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.solution.PlanningSolution
public class MeetingRoomSolution extends AbstractSolution<HardSoftScore> implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.optaplanner.core.api.domain.solution.PlanningEntityCollectionProperty
   private java.util.List<example.MeetingRquest> requestList;
   @org.optaplanner.core.api.domain.valuerange.ValueRangeProvider(id = "roomRange")
   private java.util.List<example.MeetingRoom> roomList;

   public MeetingRoomSolution()
   {
   }

   public java.util.List<example.MeetingRquest> getRequestList()
   {
      return this.requestList;
   }

   public void setRequestList(java.util.List<example.MeetingRquest> requestList)
   {
      this.requestList = requestList;
   }

   public java.util.List<example.MeetingRoom> getRoomList()
   {
      return this.roomList;
   }

   public void setRoomList(java.util.List<example.MeetingRoom> roomList)
   {
      this.roomList = roomList;
   }

   public MeetingRoomSolution(java.util.List<example.MeetingRquest> requestList,
         java.util.List<example.MeetingRoom> roomList)
   {
      this.requestList = requestList;
      this.roomList = roomList;
   }

}